// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: upload.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace gRPCFileTransfer {
  public static partial class Uploader
  {
    static readonly string __ServiceName = "upload.Uploader";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::gRPCFileTransfer.FileChunk> __Marshaller_upload_FileChunk = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPCFileTransfer.FileChunk.Parser));
    static readonly grpc::Marshaller<global::gRPCFileTransfer.Info> __Marshaller_upload_Info = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPCFileTransfer.Info.Parser));

    static readonly grpc::Method<global::gRPCFileTransfer.FileChunk, global::gRPCFileTransfer.Info> __Method_Upload = new grpc::Method<global::gRPCFileTransfer.FileChunk, global::gRPCFileTransfer.Info>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Upload",
        __Marshaller_upload_FileChunk,
        __Marshaller_upload_Info);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::gRPCFileTransfer.UploadReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for Uploader</summary>
    public partial class UploaderClient : grpc::ClientBase<UploaderClient>
    {
      /// <summary>Creates a new client for Uploader</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UploaderClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Uploader that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UploaderClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UploaderClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UploaderClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::gRPCFileTransfer.Info Upload(global::gRPCFileTransfer.FileChunk request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Upload(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::gRPCFileTransfer.Info Upload(global::gRPCFileTransfer.FileChunk request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Upload, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::gRPCFileTransfer.Info> UploadAsync(global::gRPCFileTransfer.FileChunk request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::gRPCFileTransfer.Info> UploadAsync(global::gRPCFileTransfer.FileChunk request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Upload, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UploaderClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UploaderClient(configuration);
      }
    }

  }
}
#endregion
